### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by swaapnika-guntaka** [kentore82/pyhwschema#3]
using anaconda python3

`>>> import pyhwschema`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda3/lib/python3.6/site-packages/pyhwschema/__init__.py", line 1, in <module>
    from .schema import HwSchema
  File "anaconda3/lib/python3.6/site-packages/pyhwschema/schema.py", line 3, in <module>
    from avro.schema import parse
  File "anaconda3/lib/python3.6/site-packages/avro/schema.py", line 340
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```

**Comment by swaapnika** [comment]
Thanks for the response. I’ll look for alternatives.

**Comment by kentore82** [comment]
Ive pushed a new version working with Python3. The required avro package for Python3 is `avro-python3` not `avro`. :)

**Comment by swaapnika-guntaka** [comment]
I installed avro-python3. Tried to upgrade the latest pyhwschema. It says it's already up to date. 

 >>> import pyhwschema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/remote/vgrnd104/guntaka/anaconda3/lib/python3.6/site-packages/pyhwschema/__init__.py", line 1, in <module>
    from .schema import HwSchema
  File "/remote/vgrnd104/guntaka/anaconda3/lib/python3.6/site-packages/pyhwschema/schema.py", line 3, in <module>
    from avro.schema import parse
ModuleNotFoundError: No module named 'avro.schema'
