### ISSUE TITLE
getting import error in python 3

### ISSUE THREAD

**Issue by rahul02k** [kentore82/pyhwschema#5]
The library works completely fine with python2 but throws an error when using python3.

Traceback (most recent call last):

  File "/home/user/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-54e067970929>", line 1, in <module>
    import pyhwschema

  File "/home/user/anaconda3/lib/python3.7/site-packages/pyhwschema/__init__.py", line 1, in <module>
    from .schema import HwSchema

  File "/home/user/anaconda3/lib/python3.7/site-packages/pyhwschema/schema.py", line 9, in <module>
    from avro.schema import Parse as parse

  File "/home/user/anaconda3/lib/python3.7/site-packages/avro/schema.py", line 383
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by kentore82** [comment]
Hi

As Python2.7 is approaching end of life, I should probably get around to porting this to Python 3. The main issue is the difference between the avro package in Python 2 and 3.
